#include <iostream>
#include <chrono>
#include <string>
#include <fstream>
#include <sstream>
#include <vector>
#include <map>
#include <functional>
#include <algorithm>
#include <tuple>
#include <cstdio>
#include <memory>
#include <cmath>
#include <gtest/gtest.h>